import { ComponentItem, Profile, BorrowRequest, ActivityLog, NotificationItem } from '../types';

const now = new Date();

// Helper to get ISO string offset by days/hours/minutes relative to current execution time
function offsetDate(days: number, hours: number = 0, minutes: number = 0): string {
  const d = new Date(now.getTime());
  d.setDate(d.getDate() + days);
  d.setHours(d.getHours() + hours);
  d.setMinutes(d.getMinutes() + minutes);
  return d.toISOString();
}

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'usr-faculty-01',
    email: 'faculty-01@kgkite.ac.in',
    full_name: 'Faculty User 01',
    role: 'faculty',
    faculty_id: 'FAC-KITE-01',
    department: 'ECE',
    phone: '+91 98765 00001',
    avatar_url: '/avatars/faculty.png',
    is_active: true,
    created_at: offsetDate(-15),
    updated_at: offsetDate(-15),
  },
  {
    id: 'usr-admin-02',
    email: 'admin-02@kgkite.ac.in',
    full_name: 'Admin User 02',
    role: 'admin',
    department: 'ECE / Innovation SOI',
    phone: '+91 98765 00002',
    avatar_url: '/avatars/admin.png',
    is_active: true,
    created_at: offsetDate(-15),
    updated_at: offsetDate(-15),
  },
];

export const INITIAL_COMPONENTS: ComponentItem[] = [
  {
    id: 'comp-1',
    sku: 'MCU-ARD-001',
    name: 'Arduino Uno R3',
    category: 'Microcontrollers',
    description: 'ATmega328P based microcontroller development board with 14 digital I/O pins and 6 analog inputs.',
    total_stock: 25,
    available_stock: 25,
    borrowed_stock: 0,
    cabinet: 'Lab A, Cabinet 3',
    shelf: 'Shelf 2',
    location_details: 'Lab A - Microcontroller Rack',
    image_url: 'https://images.unsplash.com/photo-1608564697071-ddf911d81370?w=400&auto=format&fit=crop&q=80',
    unit_cost: 18.50,
    created_at: offsetDate(-60),
    updated_at: offsetDate(-10),
  },
  {
    id: 'comp-2',
    sku: 'MCU-ESP-002',
    name: 'ESP32 Dev Module',
    category: 'Microcontrollers',
    description: 'Dual-core Wi-Fi & Bluetooth microcontroller board with ultra-low power co-processor.',
    total_stock: 18,
    available_stock: 18,
    borrowed_stock: 0,
    cabinet: 'Lab A, Cabinet 3',
    shelf: 'Shelf 2',
    location_details: 'Lab A - IoT Tray',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&auto=format&fit=crop&q=80',
    unit_cost: 9.75,
    created_at: offsetDate(-60),
    updated_at: offsetDate(-10),
  },
  {
    id: 'comp-3',
    sku: 'SEN-ULR-004',
    name: 'Ultrasonic Sensor HC-SR04',
    category: 'Sensors',
    description: 'Ultrasonic ranging module provides 2cm - 400cm non-contact measurement function with range accuracy up to 3mm.',
    total_stock: 40,
    available_stock: 40,
    borrowed_stock: 0,
    cabinet: 'Lab A, Cabinet 4',
    shelf: 'Shelf 1',
    location_details: 'Lab A - Sensors Drawer',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=80',
    unit_cost: 3.20,
    created_at: offsetDate(-50),
    updated_at: offsetDate(-10),
  },
  {
    id: 'comp-4',
    sku: 'SEN-PIR-008',
    name: 'PIR Motion Sensor HC-SR501',
    category: 'Sensors',
    description: 'Pyroelectric infrared sensor detects motion based on changes in infrared radiation levels.',
    total_stock: 15,
    available_stock: 15,
    borrowed_stock: 0,
    cabinet: 'Lab A, Cabinet 4',
    shelf: 'Shelf 1',
    location_details: 'Lab A - Sensors Drawer',
    image_url: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=400&auto=format&fit=crop&q=80',
    unit_cost: 2.90,
    created_at: offsetDate(-50),
    updated_at: offsetDate(-10),
  },
  {
    id: 'comp-5',
    sku: 'PAS-JMP-100',
    name: 'Jumper Wires (100pcs)',
    category: 'Passive',
    description: 'Male to Female breadboard prototyping ribbon wires 20cm length.',
    total_stock: 166,
    available_stock: 166,
    borrowed_stock: 0,
    cabinet: 'Lab A, Cabinet 1',
    shelf: 'Shelf 1',
    location_details: 'Lab A - Consumables Drawer',
    image_url: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=400&auto=format&fit=crop&q=80',
    unit_cost: 4.50,
    created_at: offsetDate(-40),
    updated_at: offsetDate(-10),
  },
  {
    id: 'comp-6',
    sku: 'MOD-REL-002',
    name: '5V Relay Module (2-Channel)',
    category: 'Modules',
    description: 'Optocoupler isolation 250V AC / 30V DC relay control board for switching heavy loads.',
    total_stock: 25,
    available_stock: 25,
    borrowed_stock: 0,
    cabinet: 'Lab A, Cabinet 2',
    shelf: 'Shelf 3',
    location_details: 'Lab A - Power Modules',
    image_url: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=400&auto=format&fit=crop&q=80',
    unit_cost: 5.80,
    created_at: offsetDate(-30),
    updated_at: offsetDate(-10),
  },
  {
    id: 'comp-7',
    sku: 'MOD-SER-009',
    name: 'SG90 Micro Servo Motor 9g',
    category: 'Modules',
    description: 'Lightweight high torque servo motor 180 degree rotation for robotics prototyping.',
    total_stock: 50,
    available_stock: 50,
    borrowed_stock: 0,
    cabinet: 'Lab A, Cabinet 4',
    shelf: 'Shelf 1',
    location_details: 'Lab A - Actuators Rack',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=400&auto=format&fit=crop&q=80',
    unit_cost: 3.90,
    created_at: offsetDate(-30),
    updated_at: offsetDate(-10),
  },
  {
    id: 'comp-8',
    sku: 'SEN-DHT-022',
    name: 'DHT22 Temperature & Humidity Sensor',
    category: 'Sensors',
    description: 'Capacitive digital humidity and calibrated temperature sensor module.',
    total_stock: 12,
    available_stock: 12,
    borrowed_stock: 0,
    cabinet: 'Lab B',
    shelf: 'Box 5',
    location_details: 'Lab B - Environmental Sensors',
    image_url: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=400&auto=format&fit=crop&q=80',
    unit_cost: 7.40,
    created_at: offsetDate(-20),
    updated_at: offsetDate(-10),
  },
];

export const INITIAL_REQUESTS: BorrowRequest[] = [
  {
    id: 'req-101',
    request_code: 'REQ-2026-0012',
    student_id: 'usr-student-1',
    student_name: 'Aravind R',
    student_register_no: '711721106001',
    student_email: 'aravind.r@kgisl.edu.in',
    component_id: 'comp-1',
    component_name: 'Arduino Uno R3',
    component_category: 'Microcontrollers',
    component_image: 'https://images.unsplash.com/photo-1608564697071-ddf911d81370?w=400&auto=format&fit=crop&q=80',
    quantity: 2,
    purpose: 'Smart Home Automation Lab Project',
    status: 'approved',
    approved_by: 'usr-faculty-1',
    approved_by_name: 'Prof. Robert Chen',
    requested_at: offsetDate(-5, -2),
    approved_at: offsetDate(-5, -1),
    expected_return_at: offsetDate(10),
    created_at: offsetDate(-5, -2),
  },
  {
    id: 'req-102',
    request_code: 'REQ-2026-0013',
    student_id: 'usr-student-2',
    student_name: 'Priya Sharma',
    student_register_no: '711721106042',
    student_email: 'priya.sharma@kgisl.edu.in',
    component_id: 'comp-2',
    component_name: 'ESP32 Dev Module',
    component_category: 'Microcontrollers',
    component_image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&auto=format&fit=crop&q=80',
    quantity: 1,
    purpose: 'IoT Agriculture Wireless Sensor Node',
    status: 'approved',
    approved_by: 'usr-faculty-1',
    approved_by_name: 'Prof. Robert Chen',
    requested_at: offsetDate(-4, -3),
    approved_at: offsetDate(-4, -2),
    expected_return_at: offsetDate(11),
    created_at: offsetDate(-4, -3),
  },
  {
    id: 'req-103',
    request_code: 'REQ-2026-0014',
    student_id: 'usr-student-3',
    student_name: 'Vikram Singh',
    student_register_no: '711721106089',
    student_email: 'vikram.singh@kgisl.edu.in',
    component_id: 'comp-4',
    component_name: 'Ultrasonic Sensor HC-SR04',
    component_category: 'Sensors',
    component_image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=80',
    quantity: 1,
    purpose: 'Autonomous Obstacle Avoidance Rover',
    status: 'pending',
    requested_at: offsetDate(-3),
    expected_return_at: offsetDate(12),
    created_at: offsetDate(-3),
  },
  {
    id: 'req-104',
    request_code: 'REQ-2026-0015',
    student_id: 'usr-student-1',
    student_name: 'Aravind R',
    student_register_no: '711721106001',
    student_email: 'aravind.r@kgisl.edu.in',
    component_id: 'comp-5',
    component_name: 'Jumper Wires (100pcs)',
    component_category: 'Passive',
    component_image: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=400&auto=format&fit=crop&q=80',
    quantity: 1,
    purpose: 'Breadboard Circuit Prototyping',
    status: 'returned',
    approved_by: 'usr-faculty-1',
    approved_by_name: 'Prof. Robert Chen',
    requested_at: offsetDate(-7, -4),
    approved_at: offsetDate(-7, -3),
    expected_return_at: offsetDate(-1),
    returned_at: offsetDate(-2),
    return_condition: 'Good Working Condition',
    created_at: offsetDate(-7, -4),
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    user_id: 'usr-admin-1',
    user_name: 'Admin User',
    user_role: 'admin',
    action: 'ADD_COMPONENT',
    entity_type: 'COMPONENT',
    details: { name: 'Arduino Mega 2560', sku: 'MCU-ARD-256' },
    severity: 'info',
    ip_address: '192.168.1.104',
    created_at: offsetDate(0, -1),
  },
  {
    id: 'log-2',
    user_id: 'usr-faculty-1',
    user_name: 'Prof. Robert Chen',
    user_role: 'faculty',
    action: 'APPROVE_REQUEST',
    entity_type: 'REQUEST',
    details: { code: 'REQ-2026-0012', student: 'Aravind R' },
    severity: 'info',
    ip_address: '192.168.1.112',
    created_at: offsetDate(-1, -2),
  },
  {
    id: 'log-3',
    user_id: 'usr-student-2',
    user_name: 'Priya Sharma',
    user_role: 'student',
    action: 'RETURN_COMPONENT',
    entity_type: 'REQUEST',
    details: { code: 'REQ-2026-0010', component: 'Ultrasonic Sensor HC-SR04' },
    severity: 'info',
    ip_address: '192.168.1.185',
    created_at: offsetDate(-2, -3),
  },
  {
    id: 'log-4',
    user_id: 'usr-student-3',
    user_name: 'Vikram Singh',
    user_role: 'student',
    action: 'SUBMIT_REQUEST',
    entity_type: 'REQUEST',
    details: { code: 'REQ-2026-0014', component: 'ESP32 Dev Module' },
    severity: 'info',
    ip_address: '192.168.1.201',
    created_at: offsetDate(-3, -4),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'usr-student-1',
    title: 'Request Approved!',
    message: 'Your request for 2x Arduino Uno R3 has been approved by Prof. Robert Chen.',
    type: 'success',
    is_read: false,
    link_url: '/student/requests',
    created_at: offsetDate(-1, -1),
  },
  {
    id: 'notif-2',
    user_id: 'usr-student-1',
    title: 'Return Confirmed',
    message: 'Return request for Ultrasonic Sensor HC-SR04 is confirmed.',
    type: 'info',
    is_read: true,
    link_url: '/student/requests',
    created_at: offsetDate(-2, -2),
  },
  {
    id: 'notif-3',
    user_id: 'usr-student-1',
    title: 'Request Received',
    message: 'Your request for ESP32 Dev Module is pending faculty approval.',
    type: 'warning',
    is_read: true,
    link_url: '/student/requests',
    created_at: offsetDate(-3, -3),
  },
];

export const INITIAL_PURCHASE_ORDERS = [
  {
    id: 'po-101',
    po_number: 'PO-2026-0891',
    supplier_name: 'Element14 India',
    component_id: 'comp-1',
    component_name: 'Arduino Uno R3',
    component_category: 'Microcontrollers' as const,
    quantity: 10,
    unit_cost: 18.50,
    total_cost: 185.00,
    purchased_by: 'usr-faculty-1',
    purchased_by_name: 'Prof. Robert Chen',
    invoice_ref: 'INV-EL14-8841',
    cabinet: 'Lab A, Cabinet 3',
    shelf: 'Shelf 2',
    status: 'delivered' as const,
    purchased_at: offsetDate(-10),
    created_at: offsetDate(-10),
  },
  {
    id: 'po-102',
    po_number: 'PO-2026-0892',
    supplier_name: 'Mouser Electronics',
    component_id: 'comp-2',
    component_name: 'ESP32 Dev Module',
    component_category: 'Microcontrollers' as const,
    quantity: 15,
    unit_cost: 9.75,
    total_cost: 146.25,
    purchased_by: 'usr-admin-1',
    purchased_by_name: 'Admin User',
    invoice_ref: 'INV-MOU-9902',
    cabinet: 'Lab A, Cabinet 3',
    shelf: 'Shelf 2',
    status: 'delivered' as const,
    purchased_at: offsetDate(-8),
    created_at: offsetDate(-8),
  },
];
